name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Sử dụng checkout phiên bản v3
      - uses: actions/checkout@v3

      # Generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: q-dat
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Push the changes using a maintained push action
      - name: Push changes
        uses: github-actions-x/push-action@v1.2.3  # Thay đổi sang hành động khác
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
